@BookfyApi_HostAddress = http://localhost:5187



###
GET {{BookfyApi_HostAddress}}/api/Categorias
Accept: application/json


###
POST {{BookfyApi_HostAddress}}/api/Categorias
Content-Type: application/json

{
  "nombre": "Categoría {{$randomInt 100 999}}"
}



###
GET {{BookfyApi_HostAddress}}/api/Autores



### Crear un nuevo Autor
POST {{BookfyApi_HostAddress}}/api/Autores
Content-Type: application/json

{
  "nombre": "Gabriel García Márquez",
  "nacionalidad": "Colombiana"
}

###

DELETE  {{BookfyApi_HostAddress}}/api/Autores/1
Accept: application/json



###

GET {{BookfyApi_HostAddress}}/api/Libros
Accept: application/json



###

POST {{BookfyApi_HostAddress}}/api/Libros
Content-Type: application/json

{
  "titulo": "Cien",
  "anioPublicacion": 1967,
  "autorId": 2,
  "categoriaId": 1
}


###
GET {{BookfyApi_HostAddress}}/api/Libros/buscar?titulo=Cien%20Años%20de%20Soledad
Accept: application/json


###
GET {{BookfyApi_HostAddress}}/api/usuario/3
Accept: application/json